import sys
from loam.const import *
from loam.obsimple import obnil

PYPLASMA_VERSION = '0.2.1'
DEFAULT_POOLS_DIR = '/var/ob/pools'
SLAW_VERSION_CURRENT = 2
PLASMA_BINARY_FILE_TYPE_SLAW = 1
PLASMA_BINARY_FILE_TYPE_POOL = 2
POOL_TCP_VERSION_CURRENT = 3

## libPlasma / plasma-retorts.h
OB_RETORTS_PLASMA_POOLS = (OB_RETORTS_PLASMA_FIRST)
POOL_NO_POOLS_DIR             = -(OB_RETORTS_PLASMA_POOLS +  400)
POOL_FILE_BADTH               = -(OB_RETORTS_PLASMA_POOLS +  500)
POOL_NULL_HOSE                = -(OB_RETORTS_PLASMA_POOLS +  505)
POOL_SEMAPHORES_BADTH         = -(OB_RETORTS_PLASMA_POOLS +  510)
POOL_MMAP_BADTH               = -(OB_RETORTS_PLASMA_POOLS +  520)
POOL_INAPPROPRIATE_FILESYSTEM = -(OB_RETORTS_PLASMA_POOLS +  525)
POOL_IN_USE                   = -(OB_RETORTS_PLASMA_POOLS +  530)
POOL_TYPE_BADTH               = -(OB_RETORTS_PLASMA_POOLS +  540)
POOL_CONFIG_BADTH             = -(OB_RETORTS_PLASMA_POOLS +  545)
POOL_WRONG_VERSION            = -(OB_RETORTS_PLASMA_POOLS +  547)
POOL_CORRUPT                  = -(OB_RETORTS_PLASMA_POOLS +  548)
POOL_POOLNAME_BADTH           = -(OB_RETORTS_PLASMA_POOLS +  550)
POOL_IMPOSSIBLE_RENAME        = -(OB_RETORTS_PLASMA_POOLS +  551)
POOL_FIFO_BADTH               = -(OB_RETORTS_PLASMA_POOLS +  555)
POOL_INVALID_SIZE             = -(OB_RETORTS_PLASMA_POOLS +  560)
POOL_NO_SUCH_POOL             = -(OB_RETORTS_PLASMA_POOLS +  570)
POOL_EXISTS                   = -(OB_RETORTS_PLASMA_POOLS +  575)
POOL_ILLEGAL_NESTING          = -(OB_RETORTS_PLASMA_POOLS +  576)
POOL_PROTOCOL_ERROR           = -(OB_RETORTS_PLASMA_POOLS +  580)
POOL_NO_SUCH_PROTEIN          = -(OB_RETORTS_PLASMA_POOLS +  635)
POOL_AWAIT_TIMEDOUT           = -(OB_RETORTS_PLASMA_POOLS +  640)
POOL_AWAIT_WOKEN              = -(OB_RETORTS_PLASMA_POOLS +  650)
POOL_WAKEUP_NOT_ENABLED       = -(OB_RETORTS_PLASMA_POOLS +  660)
POOL_PROTEIN_BIGGER_THAN_POOL = -(OB_RETORTS_PLASMA_POOLS +  700)
POOL_FROZEN                   = -(OB_RETORTS_PLASMA_POOLS +  710)
POOL_FULL                     = -(OB_RETORTS_PLASMA_POOLS +  720)
POOL_NOT_A_PROTEIN            = -(OB_RETORTS_PLASMA_POOLS +  800)
POOL_NOT_A_PROTEIN_OR_MAP     = -(OB_RETORTS_PLASMA_POOLS +  810)
POOL_CONF_WRITE_BADTH         = -(OB_RETORTS_PLASMA_POOLS +  900)
POOL_CONF_READ_BADTH          = -(OB_RETORTS_PLASMA_POOLS +  910)
POOL_SEND_BADTH               = -(OB_RETORTS_PLASMA_POOLS + 1000)
POOL_RECV_BADTH               = -(OB_RETORTS_PLASMA_POOLS + 1010)
POOL_SOCK_BADTH               = -(OB_RETORTS_PLASMA_POOLS + 1020)
POOL_SERVER_BUSY              = -(OB_RETORTS_PLASMA_POOLS + 1030)
POOL_SERVER_UNREACH           = -(OB_RETORTS_PLASMA_POOLS + 1040)
POOL_ALREADY_GANG_MEMBER      = -(OB_RETORTS_PLASMA_POOLS + 1050)
POOL_NOT_A_GANG_MEMBER        = -(OB_RETORTS_PLASMA_POOLS + 1055)
POOL_EMPTY_GANG               = -(OB_RETORTS_PLASMA_POOLS + 1060)
POOL_NULL_GANG                = -(OB_RETORTS_PLASMA_POOLS + 1070)
POOL_UNSUPPORTED_OPERATION    = -(OB_RETORTS_PLASMA_POOLS + 1100)
POOL_INVALIDATED_BY_FORK      = -(OB_RETORTS_PLASMA_POOLS + 1110)
POOL_NO_TLS                   = -(OB_RETORTS_PLASMA_POOLS + 1500)
POOL_TLS_REQUIRED             = -(OB_RETORTS_PLASMA_POOLS + 1505)
POOL_TLS_ERROR                = -(OB_RETORTS_PLASMA_POOLS + 1510)
POOL_CREATED                  =  (OB_RETORTS_PLASMA_POOLS + 10)

RANDCHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
DEFAULT_AWAIT_TIMEOUT = 3600

POOL_WAIT_FOREVER     = -1.0
POOL_NO_WAIT          =  0.0
POOL_WAIT_FOREVER_OLD =  0.0
POOL_NO_WAIT_OLD      = -1.0
TIMESTAMP_ABSOLUTE    = -1
TIMESTAMP_RELATIVE    =  0
DIRECTION_ABSOLUTE    =  0
DIRECTION_LOWER       =  1
DIRECTION_HIGHER      =  2

NIL = obnil()
BUFSIZE = 4096
DEFAULT_PORT = 65456

POOL_DIRECTORY_VERSION_CONFIG_IN_FILE = 4
POOL_DIRECTORY_VERSION_CONFIG_IN_MMAP = 5
POOL_DIRECTORY_VERSION_SINGLE_FILE    = 6

POOL_FLAG_STOP_WHEN_FULL = 1 << 0
POOL_FLAG_FROZEN         = 1 << 1
POOL_FLAG_AUTO_DISPOSE   = 1 << 2
POOL_FLAG_CHECKSUM       = 1 << 3
POOL_FLAG_SYNC           = 1 << 32

KILOBYTE = 2**10
MEGABYTE = 2**20
GIGABYTE = 2**30
TERABYTE = 2**40
POOL_SIZE_TINY = 10 * KILOBYTE
POOL_SIZE_SMALL = 1 * MEGABYTE
POOL_SIZE_MEDIUM = 10 * MEGABYTE
POOL_SIZE_LARGE = 100 * MEGABYTE
POOL_SIZE_OBSCENE = 2 * GIGABYTE
if sys.maxsize > 2**32:
    POOL_SIZE_MAX = 8 * TERABYTE
else:
    POOL_SIZE_MAX = 2 * GIGABYTE

HOSE_STATE_INITIAL     = 0
HOSE_STATE_PARTICIPATE = 1
HOSE_STATE_FINAL       = 2
